// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Action {
    /**
     * Creates a new Action instance.
     * @param {Partial<Action>} [$$source = {}] - The source object to create the Action.
     */
    constructor($$source = {}) {
        if (!("Type" in $$source)) {
            /**
             * either ToDevice or FromDevice. If type is "" the action is ignored
             * @member
             * @type {string}
             */
            this["Type"] = "";
        }
        if (!("FileName" in $$source)) {
            /**
             * only populated if type is ToDevice
             * @member
             * @type {string}
             */
            this["FileName"] = "";
        }
        if (!("DownloadCallback" in $$source)) {
            /**
             * only populated if type is FromDevice
             * @member
             * @type {any | null}
             */
            this["DownloadCallback"] = null;
        }
        if (!("Data" in $$source)) {
            /**
             * only populated if type is ToDevice
             * @member
             * @type {string}
             */
            this["Data"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Action instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Action}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Data" in $$parsedSource) {
            $$parsedSource["Data"] = $$createField3_0($$parsedSource["Data"]);
        }
        return new Action(/** @type {Partial<Action>} */($$parsedSource));
    }
}

export class Device {
    /**
     * Creates a new Device instance.
     * @param {Partial<Device>} [$$source = {}] - The source object to create the Device.
     */
    constructor($$source = {}) {
        if (!("Ip" in $$source)) {
            /**
             * main identifier
             * @member
             * @type {string}
             */
            this["Ip"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * extracted from user agent
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("LastPing" in $$source)) {
            /**
             * if we've gone more than 3 seconds without a ping, we dont include it
             * @member
             * @type {number}
             */
            this["LastPing"] = 0;
        }
        if (!("PendingAction" in $$source)) {
            /**
             * @member
             * @type {Action}
             */
            this["PendingAction"] = (new Action());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Device instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Device}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("PendingAction" in $$parsedSource) {
            $$parsedSource["PendingAction"] = $$createField3_0($$parsedSource["PendingAction"]);
        }
        return new Device(/** @type {Partial<Device>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Action.createFrom;
