// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App struct
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} uuid
 * @returns {$CancellablePromise<void>}
 */
export function CloseTransfer(uuid) {
    return $Call.ByID(2077077968, uuid);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetLocalIp() {
    return $Call.ByID(153419183);
}

/**
 * @param {string} uuid
 * @returns {$CancellablePromise<[number, number, number, string, string, string, boolean, number]>}
 */
export function GetTransferStatus(uuid) {
    return $Call.ByID(3426869438, uuid);
}

/**
 * @returns {$CancellablePromise<$models.Device[]>}
 */
export function GetValidDevices() {
    return $Call.ByID(2674225862).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} deviceIp
 * @returns {$CancellablePromise<void>}
 */
export function RecvFile(deviceIp) {
    return $Call.ByID(639282611, deviceIp);
}

/**
 * @param {string} deviceIp
 * @returns {$CancellablePromise<void>}
 */
export function SendFile(deviceIp) {
    return $Call.ByID(4197026393, deviceIp);
}

// Private type creation functions
const $$createType0 = $models.Device.createFrom;
const $$createType1 = $Create.Array($$createType0);
