// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as io$0 from "../io/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

export class Action {
    /**
     * Creates a new Action instance.
     * @param {Partial<Action>} [$$source = {}] - The source object to create the Action.
     */
    constructor($$source = {}) {
        if (!("Type" in $$source)) {
            /**
             * either ToDevice or FromDevice. If type is "" the action is ignored
             * @member
             * @type {string}
             */
            this["Type"] = "";
        }
        if (!("FileName" in $$source)) {
            /**
             * always set if type is ToDevice, set when the download has begun in case of FromDevice
             * @member
             * @type {string}
             */
            this["FileName"] = "";
        }
        if (!("UUID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["UUID"] = "";
        }
        if (!("UploadPreWriterStatus" in $$source)) {
            /**
             * status of a FromDevice action before a ProgressedWriter has been created, either RequestReceived or Canceled
             * @member
             * @type {string}
             */
            this["UploadPreWriterStatus"] = "";
        }
        if (!("Begun" in $$source)) {
            /**
             * Whether the device already has been informed of the download
             * @member
             * @type {boolean}
             */
            this["Begun"] = false;
        }
        if (!("BegunTime" in $$source)) {
            /**
             * Timestamp when the download begun
             * @member
             * @type {time$0.Time}
             */
            this["BegunTime"] = null;
        }
        if (!("UploadReader" in $$source)) {
            /**
             * only populated if type is ToDevice
             * @member
             * @type {io$0.ReadSeekCloser}
             */
            this["UploadReader"] = null;
        }
        if (!("DownloadBegins" in $$source)) {
            /**
             * only populated if type is FromDevice, called when the download has begun.
             * @member
             * @type {any | null}
             */
            this["DownloadBegins"] = null;
        }
        if (!("ProgressedWriter" in $$source)) {
            /**
             * set when the download has begun. Should NOT be written to.
             * @member
             * @type {ProgressedWriter | null}
             */
            this["ProgressedWriter"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Action instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Action}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("ProgressedWriter" in $$parsedSource) {
            $$parsedSource["ProgressedWriter"] = $$createField8_0($$parsedSource["ProgressedWriter"]);
        }
        return new Action(/** @type {Partial<Action>} */($$parsedSource));
    }
}

export class Device {
    /**
     * Creates a new Device instance.
     * @param {Partial<Device>} [$$source = {}] - The source object to create the Device.
     */
    constructor($$source = {}) {
        if (!("Ip" in $$source)) {
            /**
             * main identifier
             * @member
             * @type {string}
             */
            this["Ip"] = "";
        }
        if (!("Name" in $$source)) {
            /**
             * extracted from user agent
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("LastPing" in $$source)) {
            /**
             * if we've gone more than 3 seconds without a ping, we dont include it
             * @member
             * @type {number}
             */
            this["LastPing"] = 0;
        }
        if (!("PendingAction" in $$source)) {
            /**
             * @member
             * @type {Action}
             */
            this["PendingAction"] = (new Action());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Device instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Device}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("PendingAction" in $$parsedSource) {
            $$parsedSource["PendingAction"] = $$createField3_0($$parsedSource["PendingAction"]);
        }
        return new Device(/** @type {Partial<Device>} */($$parsedSource));
    }
}

export class ProgressedWriter {
    /**
     * Creates a new ProgressedWriter instance.
     * @param {Partial<ProgressedWriter>} [$$source = {}] - The source object to create the ProgressedWriter.
     */
    constructor($$source = {}) {
        if (!("Size" in $$source)) {
            /**
             * Size can be set during initalization and may be used to track the expected size of the data to be written to the writer.
             * @member
             * @type {number}
             */
            this["Size"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgressedWriter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProgressedWriter}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProgressedWriter(/** @type {Partial<ProgressedWriter>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ProgressedWriter.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = Action.createFrom;
