// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * ReadSeekCloser is the interface that groups the basic Read, Seek and Close
 * methods.
 * @typedef {$models.ReadSeekCloser} ReadSeekCloser
 */
