// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalIp() {
  return window['go']['main']['App']['GetLocalIp']();
}

export function GetValidDevices() {
  return window['go']['main']['App']['GetValidDevices']();
}

export function RecvFile(arg1) {
  return window['go']['main']['App']['RecvFile'](arg1);
}

export function SendFile(arg1) {
  return window['go']['main']['App']['SendFile'](arg1);
}
