// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLocalIp():Promise<string>;

export function GetValidDevices():Promise<Array<main.Device>>;

export function RecvFile(arg1:string):Promise<void>;

export function SendFile(arg1:string):Promise<void>;
